### ISSUE TITLE
Simple examples in the README

### ISSUE THREAD

**Issue by bararchy** [giuse/neuroevo#1]
Hi, 
It would be nice to have some simple example straight out in the README, like xor example, and maybe another one for both RNN and FFNN

**Comment by giuse** [comment]
Hi bararchy,
You're absolutely right. After long hiatus, I should get back to the `neuroevo` gem in the next weeks, and I'll copy a snippet from the specs into the README as I usually like to find it too :) not only, but I'll do the same with my new `data_modeler` (now production ready!). Thanks!

**Comment by giuse** [comment]
Hi, thanks for pointing this out and sorry for the delay. I'm back on neuroevolution (finally!).
Here's the commit closing this issue: b4811fdd4a8c9a3e3640e8573f2bc387e54bb1dd
Thanks for using neuroevo! :)
